
//Converted with http://www.percederberg.net/tools/text_converter.html to C-String Text and saved as char

const char index[] PROGMEM = {
"<HTML><HEAD>\n<link rel=\"icon\" href=\"data:;base64,iVBORw0KGgo=\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=2.0, user-scalable=yes\">\n<tilte><h1>NanoESP RGB</h1></tilte>\n</HEAD>\n<BODY bgcolor=\"#FFFF99\">\n<HR>\n\nChange the Color<BR>\nof the RGB-LED\n<BR><BR>\n<form action=\"/setcolor\">\n\t<input type=\"color\" id= \"rgb\" name=\"rgb\" onchange=\"return sendForm(this.form);\"><BR>\n</form>\n<HR>\n<a href=\"/config\">Config Menu</a><br>\n<HR>\n</font>\n<textarea id=\"msg\" name=\"message\" rows=\"5\" cols=\"40\">\n\n</textarea>\n\n<script language=\"JavaScript\">\nfunction sendForm(form) {\n  var formData =\"\";\n  \tfor (var i = 0, d, v; i < form.elements.length; i++) {\n\t\td = form.elements[i];\n\t\tif (d.name && d.value) {\n\t\t\tv = (d.type == \"checkbox\" || d.type == \"radio\" ? (d.checked ? d.value : \"\") : d.value);\n\t\t\tif (v) formData += d.name + \"=\" + escape(v) + \"&\";\n\t\t}\n\t}\n  var xhr = new XMLHttpRequest();\n  xhr.open('POST', form.action, true);\n  xhr.send(formData);\n  return false;\n}\n\n</script>\n\n</BODY>\n</HTML>\0"
};

const char config[] PROGMEM = {
"<HTML>\n<HEAD>\n<link rel=\"shortcut icon\" href=\"data:image/x-icon;,\" type=\"image/x-icon\"> \n<meta name=\"viewport\" content=\"width=device-width, user-scalable=yes\">\n<tilte><h1>NanoESP Configuration</h1></tilte>\n</HEAD>\n<BODY bgcolor=\"#FFFF99\">\n<HR>\n<form action=\"/setconfig\">\n  <table>\n      <tr>\n\t\t<th>Station</th>\n\t\t<td></td>\t\n\t  </tr>\n\t  <tr>\n        <td>SSID:</td>\n        <td>\n\t\t\t<input type=\"search\" list=\"ssid\" name=\"ssid\"/>\n\t\t\t<datalist  id=\"ssid\">\t\t\n\t\t\t</datalist>\n\t\t\t</select>\n\t\t</td>\n      </tr>\n      <tr>\n        <td>PASSWORD:</td>\n        <td><input type=\"password\" name=\"pass\"></td>\n      </tr>\n      <tr>\n\t\t<th>AccessPoint</th>\n\t\t<td></td>\t\n\t  </tr>\n\t  <tr>\n\t\t<td>AccessPoint SSID:</td>\n\t\t<td><input type=\"text\" name=\"apssid\"></td>\n      </tr>\n      <tr>\n        <td>AccessPoint Password:</td>\n        <td><input type=\"text\" name=\"apass\" \"mypassword\"></td>\n      </tr>\t  \n      <tr>\n\t\t<td></td>\n\t\t<td><input type=\"submit\" onclick=\"return sendForm(this.form);\"></td>\n      </tr>\n    </table>\n</form>\n<hr><a href=\"/\">Main Page</a><br>\n<HR>\n<textarea id=\"msg\" name=\"message\" rows=\"5\" cols=\"40\">\n\n</textarea>\n\n<script language=\"JavaScript\">\nfunction sendForm(form) {\n  var formData =\"\";\n  \tfor (var i = 0, d, v; i < form.elements.length; i++) {\n\t\td = form.elements[i];\n\t\tif (d.name && d.value) {\n\t\t\tv = (d.type == \"checkbox\" || d.type == \"radio\" ? (d.checked ? d.value : \"\") : d.value);\n\t\t\tif (v) formData += d.name + \"=\" + escape(v) + \"&\";\n\t\t}\n\t}\n  var xhr = new XMLHttpRequest();\n  xhr.open('POST', form.action, true);\n  xhr.send(formData);\n  return false;\n}\nvar source = new EventSource(\"/eventssid\");\n\nsource.addEventListener('ssid', function(e) {\n ssidSelect = document.getElementById('ssid');\n ssidSelect.innerHTML +='<option value=\"'+e.data+'\"/>';\n}, false);\n\nsource.addEventListener('msg', function(e) {\n\tdocument.getElementById('msg').value += e.data;\n}, false);\n\n</script>\n\n</BODY>\n</HTML>\0"
};

const char error404[] PROGMEM = {
"<HTML><HEAD>\n<link rel=\"shortcut icon\" href=\"data:image/x-icon;,\" type=\"image/x-icon\"> \n<title>\nError\n</title>\n</HEAD>\n<BODY bgcolor=\"#FFFF99\" text=\"#000000\">\n<h1>Error 404: File or Page not found</h1>\n<HR><BR>\n<a href=\"/\">Main Page</a><br>\n<br>\n<br>\n<HR><BR>\n</body>\n</HTML>\0"
};


